"""Constants used by the mitsubishi-wf-rac component."""

from homeassistant.const import CONF_ICON, CONF_NAME, CONF_TYPE
from homeassistant.components.climate.const import (
    HVACMode,
    ClimateEntityFeature,
    HVACMode,
    FAN_AUTO,
)

DOMAIN = "mitsubishi_wf_rac"
DEVICES = "wf-rac-devices"

CONF_OPERATOR_ID = "operator_id"
CONF_AIRCO_ID = "airco_id"
ATTR_DEVICE_ID = "device_id"
ATTR_CONNECTED_ACCOUNTS = "connected_accounts"

ATTR_INSIDE_TEMPERATURE = "inside_temperature"
ATTR_OUTSIDE_TEMPERATURE = "outside_temperature"

API="api"
CURRENT_PRESET_MODE = "current_preset_mode"
HORIZONTAL_SWING_MODE = "horizontal_swing_mode"
VERTICAL_SWING_MODE = "vertical_swing_mode"
HVAC_MODE="hvac_mode"
FAN_MODE="fan_mode"
DEVICES="devices"
NAME="name"
NUMBER_OF_PRESET_MODES = 4
PRESET_MODES="preset_modes"
STORE="store"
TEMPERATURE="temperature"

SENSOR_TYPE_TEMPERATURE = "temperature"

SENSOR_TYPES = {
    ATTR_INSIDE_TEMPERATURE: {
        CONF_NAME: "Inside Temperature",
        CONF_ICON: "mdi:thermometer",
        CONF_TYPE: SENSOR_TYPE_TEMPERATURE,
    },
    ATTR_OUTSIDE_TEMPERATURE: {
        CONF_NAME: "Outside Temperature",
        CONF_ICON: "mdi:thermometer",
        CONF_TYPE: SENSOR_TYPE_TEMPERATURE,
    },
}

SERVICE_SET_HORIZONTAL_SWING_MODE = "set_horizontal_swing_mode"
SERVICE_SET_VERTICAL_SWING_MODE = "set_vertical_swing_mode"

SUPPORT_FLAGS = (
    ClimateEntityFeature.TARGET_TEMPERATURE
    | ClimateEntityFeature.SWING_MODE
    | ClimateEntityFeature.FAN_MODE
    | ClimateEntityFeature.PRESET_MODE
)

SUPPORTED_HVAC_MODES = [
    HVACMode.OFF,
    HVACMode.AUTO,
    HVACMode.COOL,
    HVACMode.DRY,
    HVACMode.HEAT,
    HVACMode.FAN_ONLY,
]

HVAC_TRANSLATION = {
    HVACMode.AUTO: 0,
    HVACMode.COOL: 1,
    HVACMode.HEAT: 2,
    HVACMode.FAN_ONLY: 3,
    HVACMode.DRY: 4,
}

SWING_3D_AUTO = "3D Auto"
SWING_VERTICAL_POSITION_1 = "Hoog"
SWING_VERTICAL_POSITION_2 = "Middel"
SWING_VERTICAL_POSITION_3 = "Normaal"
SWING_VERTICAL_POSITION_4 = "Laag"
SWING_VERTICAL_AUTO = "Boven/ Beneden Auto"

SWING_HORIZONTAL_POSITION_1 = "Links-Links"
SWING_HORIZONTAL_POSITION_2 = "Midden-Midden"
SWING_HORIZONTAL_POSITION_3 = "Center-Center"
SWING_HORIZONTAL_POSITION_4 = "Midden-Rechts"
SWING_HORIZONTAL_POSITION_5 = "Rechts-Rechts"
SWING_HORIZONTAL_POSITION_6 = "Links-Rechts"
SWING_HORIZONTAL_POSITION_7 = "Rechts-Links"
SWING_HORIZONTAL_AUTO = "Links/Rechts Auto"


SWING_MODE_TRANSLATION = {
    SWING_VERTICAL_AUTO: 0,
    SWING_VERTICAL_POSITION_1: 1,
    SWING_VERTICAL_POSITION_2: 2,
    SWING_VERTICAL_POSITION_3: 3,
    SWING_VERTICAL_POSITION_4: 4,
}

SUPPORT_SWING_MODES = [
    SWING_VERTICAL_AUTO,
    SWING_VERTICAL_POSITION_1,
    SWING_VERTICAL_POSITION_2,
    SWING_VERTICAL_POSITION_3,
    SWING_VERTICAL_POSITION_4,
    SWING_3D_AUTO,
]

HORIZONTAL_SWING_MODE_TRANSLATION = {
    SWING_HORIZONTAL_AUTO: 0,
    SWING_HORIZONTAL_POSITION_1: 1,
    SWING_HORIZONTAL_POSITION_2: 2,
    SWING_HORIZONTAL_POSITION_3: 3,
    SWING_HORIZONTAL_POSITION_4: 4,
    SWING_HORIZONTAL_POSITION_5: 5,
    SWING_HORIZONTAL_POSITION_6: 6,
    SWING_HORIZONTAL_POSITION_7: 7,
}

SUPPORT_HORIZONTAL_SWING_MODES = [
    SWING_HORIZONTAL_AUTO,
    SWING_HORIZONTAL_POSITION_1,
    SWING_HORIZONTAL_POSITION_2,
    SWING_HORIZONTAL_POSITION_3,
    SWING_HORIZONTAL_POSITION_4,
    SWING_HORIZONTAL_POSITION_5,
    SWING_HORIZONTAL_POSITION_6,
    SWING_HORIZONTAL_POSITION_7,
]


FAN_MODE_1 = "1 Laagste"
FAN_MODE_2 = "2 Laag"
FAN_MODE_3 = "3 Hoog"
FAN_MODE_4 = "4 Hoogst"

FAN_MODE_TRANSLATION = {
    FAN_AUTO: 0,
    FAN_MODE_1: 1,
    FAN_MODE_2: 2,
    FAN_MODE_3: 3,
    FAN_MODE_4: 4,
}

SUPPORTED_FAN_MODES = [
    FAN_AUTO,
    FAN_MODE_1,
    FAN_MODE_2,
    FAN_MODE_3,
    FAN_MODE_4,
]


OPERATION_LIST = {
    # HVAC_MODE_OFF: "Off",
    HVACMode.HEAT: "Heat",
    HVACMode.COOL: "Cool",
    HVACMode.AUTO: "Auto",
    HVACMode.DRY: "Dry",
    HVACMode.FAN_ONLY: "Fan",
}
