class Aircon:
    IndoorTemp: float
    OutdoorTemp: float
    PresetTemp: float
    Electric: float
    ModelNr: int
    Operation: bool
    OperationMode: int
    AirFlow: int
    WindDirectionUD: int
    WindDirectionLR: int
    Entrust: bool
    ErrorCode: str
    Vacant: bool